Attaching to dataclay_dsjava_1
[36mdsjava_1       |[0m 2020-05-08T07:35:26,331 DEBUG [util.Configuration] [main] [Configuration$Flags:414] Looking for environment variable DATACLAYGLOBALCONFIG
[36mdsjava_1       |[0m 2020-05-08T07:35:26,333 DEBUG [util.Configuration] [main] [Configuration$Flags:417] Found DATACLAYGLOBALCONFIG defined at null. Trying to read.
[36mdsjava_1       |[0m 2020-05-08T07:35:26,346 DEBUG [util.Configuration] [main] [Configuration$Flags:433] Cannot find environment variable DATACLAYGLOBALCONFIG. Trying default location /home/dataclayusr/dataclay/cfgfiles/global.properties
[36mdsjava_1       |[0m 2020-05-08T07:35:26,346 INFO [util.Configuration] [main] [Configuration$Flags:531] Using global.properties file found at /home/dataclayusr/dataclay/cfgfiles/global.properties
[36mdsjava_1       |[0m 2020-05-08T07:35:26,346 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: DB_HANDLER_TYPE_FOR_DATASERVICES
[36mdsjava_1       |[0m 2020-05-08T07:35:26,346 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: DB_HANDLER_TYPE_FOR_DATASERVICES=SQLITE
[36mdsjava_1       |[0m 2020-05-08T07:35:26,347 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: STORAGE_PATH
[36mdsjava_1       |[0m 2020-05-08T07:35:26,347 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: STORAGE_PATH=/dataclay/storage
[36mdsjava_1       |[0m 2020-05-08T07:35:26,360 INFO [CfgDataService] [main] [CfgDataServiceEnvLoader:131] Resolved inet address : 581cd2351ab9/172.27.0.3
[36mdsjava_1       |[0m 2020-05-08T07:35:26,360 INFO [CfgDataService] [main] [CfgDataServiceEnvLoader:132] Resolved hostname : 172.27.0.3
[36mdsjava_1       |[0m 2020-05-08T07:35:26,391 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: CHECK_LOG4J_DEBUG
[36mdsjava_1       |[0m 2020-05-08T07:35:26,391 DEBUG [util.Configuration] [main] [Configuration$Flags:450] Found environment variable set in global.properties: CHECK_LOG4J_DEBUG=true
[36mdsjava_1       |[0m 2020-05-08T07:35:26,403 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: MAX_ENTRIES_DATASERVICE_CACHE
[36mdsjava_1       |[0m 2020-05-08T07:35:26,403 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: MAX_ENTRIES_DATASERVICE_CACHE=10000
[36mdsjava_1       |[0m 2020-05-08T07:35:26,403 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: LRU_LOAD_FACTOR
[36mdsjava_1       |[0m 2020-05-08T07:35:26,404 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: LRU_LOAD_FACTOR=0.75
[36mdsjava_1       |[0m 2020-05-08T07:35:26,422 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: MAX_ENTRIES_CLIENT_CACHE
[36mdsjava_1       |[0m 2020-05-08T07:35:26,422 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: MAX_ENTRIES_CLIENT_CACHE=10000
[36mdsjava_1       |[0m 2020-05-08T07:35:26,423 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: MEMMGMT_PRESSURE_FRACTION
[36mdsjava_1       |[0m 2020-05-08T07:35:26,423 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: MEMMGMT_PRESSURE_FRACTION=0.7
[36mdsjava_1       |[0m 2020-05-08T07:35:26,424 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: MEMMGMT_MIN_OBJECT_TIME
[36mdsjava_1       |[0m 2020-05-08T07:35:26,424 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: MEMMGMT_MIN_OBJECT_TIME=500
[36mdsjava_1       |[0m 2020-05-08T07:35:26,428 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: LRU_BYDATE_TIMEUNIT_VALUE
[36mdsjava_1       |[0m 2020-05-08T07:35:26,428 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: LRU_BYDATE_TIMEUNIT_VALUE=1
[36mdsjava_1       |[0m 2020-05-08T07:35:26,438 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: EE_PERSISTENT_INFO_PATH
[36mdsjava_1       |[0m 2020-05-08T07:35:26,439 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: EE_PERSISTENT_INFO_PATH=/home/dataclayusr/dataclay/
[36mdsjava_1       |[0m 2020-05-08T07:35:26,474 INFO [DataService] [main] [DataService:189] Initialized execution environment ID :664a2208-5613-479e-8d56-69e0f09634cb
[36mdsjava_1       |[0m 2020-05-08T07:35:26,474 INFO [DataService] [main] [DataService:190] Initialized storage location ID :f4166767-d25b-44bc-a909-ec8dcf5cd0a0
[36mdsjava_1       |[0m 2020-05-08T07:35:26,475 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: MAX_MESSAGE_SIZE
[36mdsjava_1       |[0m 2020-05-08T07:35:26,475 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: MAX_MESSAGE_SIZE=2147483647
[36mdsjava_1       |[0m 2020-05-08T07:35:28,095 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: MAX_RETRY_AUTOREGISTER
[36mdsjava_1       |[0m 2020-05-08T07:35:28,095 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: MAX_RETRY_AUTOREGISTER=10
[36mdsjava_1       |[0m 2020-05-08T07:35:28,095 INFO [DataClayRuntime] [main] [DataClayRuntime:163] Connecting to LM at logicmodule:11034 ...
[36mdsjava_1       |[0m 2020-05-08T07:35:28,167 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: SSL_CLIENT_TRUSTED_CERTIFICATES
[36mdsjava_1       |[0m 2020-05-08T07:35:28,167 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: SSL_CLIENT_TRUSTED_CERTIFICATES=null
[36mdsjava_1       |[0m 2020-05-08T07:35:28,167 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: SSL_CLIENT_CERTIFICATE
[36mdsjava_1       |[0m 2020-05-08T07:35:28,167 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: SSL_CLIENT_CERTIFICATE=null
[36mdsjava_1       |[0m 2020-05-08T07:35:28,167 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: SSL_CLIENT_KEY
[36mdsjava_1       |[0m 2020-05-08T07:35:28,167 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: SSL_CLIENT_KEY=null
[36mdsjava_1       |[0m 2020-05-08T07:35:28,371 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: LM_SERVICE_ALIAS_HEADERMSG
[36mdsjava_1       |[0m 2020-05-08T07:35:28,371 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: LM_SERVICE_ALIAS_HEADERMSG=logicmodule1
[36mdsjava_1       |[0m 2020-05-08T07:35:28,732 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: MAX_RETRIES_LOGICMODULE
[36mdsjava_1       |[0m 2020-05-08T07:35:28,732 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: MAX_RETRIES_LOGICMODULE=1
[36mdsjava_1       |[0m 2020-05-08T07:35:29,803 INFO [DataClayRuntime] [main] [DataClayRuntime:166] Connected to LM!
[36mdsjava_1       |[0m 2020-05-08T07:35:29,803 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: MEMORY_GC_ENABLED
[36mdsjava_1       |[0m 2020-05-08T07:35:29,804 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: MEMORY_GC_ENABLED=true
[36mdsjava_1       |[0m 2020-05-08T07:35:29,804 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: MEMMGMT_CHECK_TIME_INTERVAL
[36mdsjava_1       |[0m 2020-05-08T07:35:29,804 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: MEMMGMT_CHECK_TIME_INTERVAL=5000
[36mdsjava_1       |[0m 2020-05-08T07:35:29,818 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: PREFETCHING_ENABLED
[36mdsjava_1       |[0m 2020-05-08T07:35:29,819 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: PREFETCHING_ENABLED=false
[36mdsjava_1       |[0m 2020-05-08T07:35:30,072 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: GLOBAL_GC_ENABLED
[36mdsjava_1       |[0m 2020-05-08T07:35:30,073 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: GLOBAL_GC_ENABLED=true
[36mdsjava_1       |[0m 2020-05-08T07:35:30,075 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: DEFAULT_GLOBALGC_CACHE_PATH
[36mdsjava_1       |[0m 2020-05-08T07:35:30,076 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: DEFAULT_GLOBALGC_CACHE_PATH=/home/dataclayusr/dataclay/
[36mdsjava_1       |[0m 2020-05-08T07:35:30,076 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: GLOBALGC_COLLECTOR_INITIAL_DELAY_HOURS
[36mdsjava_1       |[0m 2020-05-08T07:35:30,077 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: GLOBALGC_COLLECTOR_INITIAL_DELAY_HOURS=12
[36mdsjava_1       |[0m 2020-05-08T07:35:30,141 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: GLOBALGC_CHECK_REMOTE_PENDING
[36mdsjava_1       |[0m 2020-05-08T07:35:30,141 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: GLOBALGC_CHECK_REMOTE_PENDING=4000
[36mdsjava_1       |[0m 2020-05-08T07:35:30,142 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: GLOBALGC_PROCESS_COUNTINGS_INTERVAL
[36mdsjava_1       |[0m 2020-05-08T07:35:30,142 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: GLOBALGC_PROCESS_COUNTINGS_INTERVAL=2000
[36mdsjava_1       |[0m 2020-05-08T07:35:30,142 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: GLOBALGC_CHECK_TIME_INTERVAL
[36mdsjava_1       |[0m 2020-05-08T07:35:30,142 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: GLOBALGC_CHECK_TIME_INTERVAL=86400000
[36mdsjava_1       |[0m 2020-05-08T07:35:30,142 DEBUG [util.Configuration] [main] [Configuration$Flags:447] Looking for env variable set in global.properties: STATE_FILE_PATH
[36mdsjava_1       |[0m 2020-05-08T07:35:30,142 DEBUG [util.Configuration] [main] [Configuration$Flags:486] Not found environment variable set in global.properties, using default: STATE_FILE_PATH=state.txt
[36mdsjava_1       |[0m 2020-05-08T07:35:33,875 DEBUG [DataService] [DS1-1-thread-1] [DataService:285] Associating 5c1c62dc-97ef-4f5b-a5c7-758eda5a2428 to DS1
[36mdsjava_1       |[0m 2020-05-08T07:36:43,232 DEBUG [es.bsc.dataclay.dbhandler.sql.sqlite.SQLiteHandler] [DS1-1-thread-2] [SQLiteHandler:47] SQLITE DB URL = jdbc:sqlite:/dataclay/storage/664a2208-5613-479e-8d56-69e0f09634cb
[36mdsjava_1       |[0m 2020-05-08T07:36:43,458 DEBUG [es.bsc.dataclay.dbhandler.sql.sqlite.SQLiteHandler] [DS1-1-thread-2] [SQLiteHandler:47] SQLITE DB URL = jdbc:sqlite:/dataclay/storage/5c1c62dc-97ef-4f5b-a5c7-758eda5a2428
[36mdsjava_1       |[0m 2020-05-08T07:41:22,396 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:22,506 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:22,575 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:22,639 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:22,669 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:22,731 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:22,752 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:22,808 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:22,832 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:22,893 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:39,406 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:39,466 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:39,474 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:39,535 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:39,543 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:39,600 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:39,615 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[36mdsjava_1       |[0m 2020-05-08T07:41:39,674 DEBUG [exceptions] [DS1-1-thread-3] [Utils:1772] [==EXCEPTION==] Sending DataClayException GRPC response: 
[36mdsjava_1       |[0m es.bsc.dataclay.exceptions.dbhandler.DbObjectNotExistException: Object with ID: f2a3205d-2a4f-37eb-9159-a3ded7b84961 cannot be found
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dbhandler.sql.SQLHandler.get(SQLHandler.java:188) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.storagelocation.StorageLocationService.get(StorageLocationService.java:135) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.dataservice.DataService.get(DataService.java:2287) ~[dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.services.dataservice.DataServiceService.getFromDB(DataServiceService.java:1047) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at es.bsc.dataclay.communication.grpc.generated.dataservice.DataServiceGrpc$MethodHandlers.invoke(DataServiceGrpc.java:3398) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [dataclay.jar:?]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
[36mdsjava_1       |[0m 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
